### ISSUE TITLE
TV Aspect Ratio Wrong 

### ISSUE THREAD

**Issue by curphey** [crashappsec/www-qa-issues#10]
Its 1.45 and should be 2 
<img width="709" alt="Screenshot 2022-09-04 at 15 38 14" src="https://user-images.githubusercontent.com/143776/188319074-c65c3f2d-31c9-4b1a-85de-3d357d581081.png">

**Comment by alexdunphy** [comment]
This is fixed - the grid image with the wrong aspect ratio has been replaced with a CSS pattern.

@curphey If you get a chance, could you publish the home page at https://app-eu1.hubspot.com/content/25939634/edit/53439940813/content? It's currently under ['Staged draft' here](https://app-eu1.hubspot.com/content/25939634/staging/domain/49440753384/manage/stagedDraft), instead of 'Staged proof' like the other site pages.
