### ISSUE TITLE
Update JQuery Library 

### ISSUE THREAD

**Issue by curphey** [crashappsec/www-qa-issues#6]
If JQuery is being used it should be upgraded to the latest version HubSpot supports. If not disable it. 

https://developers.hubspot.com/cms/guides/jquery/upgrade#

**Comment by nettrino** [comment]
For reference,  jquery version 1.11.2 suffers from the following issues:

[CVE-2015-9251](https://nvd.nist.gov/vuln/detail/CVE-2015-9251): 3rd party CORS request may execute 
[CVE-2015-9251](https://nvd.nist.gov/vuln/detail/CVE-2015-9251): parseHTML() executes scripts in event handlers 
[CVE-2019-11358](https://nvd.nist.gov/vuln/detail/CVE-2019-11358): jQuery before 3.4.0, as used in Drupal, Backdrop CMS, and other products, mishandles jQuery.extend(true, {}, ...) because of Object.prototype pollution 
[CVE-2020-11022](https://nvd.nist.gov/vuln/detail/CVE-2020-11022): Regex in its `jQuery.htmlPrefilter` sometimes may introduce XSS 
[CVE-2020-11023](https://nvd.nist.gov/vuln/detail/CVE-2020-11023): Regex in its `jQuery.htmlPrefilter` sometimes may introduce XSS
